/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aryaaazr_
 */
public class DaftarKategori extends javax.swing.JFrame {

    /**
     * Creates new form DaftarBarang
     */
    static DefaultTableModel model;
    static String id_kategori;
    static String nama_kategori;
    static String selectedKategoriID;

    public DaftarKategori() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tb_kategori.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 12));
        tb_kategori.getTableHeader().setOpaque(false);
        tb_kategori.getTableHeader().setBackground(new Color(34, 48, 96));
        tb_kategori.getTableHeader().setForeground(new Color(255, 255, 255));
        tb_kategori.getRowHeight(25);
        tampilkan();
        
        this.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e){
            Barang.refreshCombo();
            }
          }
        );
    }

    public static void tampilkan() {
        String[] judul = {"ID Kategori", "Nama Kategori"};
        model = new DefaultTableModel(judul, 0);
        tb_kategori.setModel(model);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_kategori");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void reset() {
        txt_idkategori.setText("");
        txt_namakategori.setText("");
    }
    public void windowsClosing(WindowEvent e){
        System.out.println("ok");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kategori = new javax.swing.JTable();
        btnTambah = new javax.swing.JLabel();
        txt_namakategori = new javax.swing.JTextField();
        txt_idkategori = new javax.swing.JTextField();
        labelKategori1 = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        fieldIdBarang1 = new javax.swing.JLabel();
        fieldIdBarang = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_kategori.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_kategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_kategori);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 580, 220));

        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/add (4) 1.png"))); // NOI18N
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTambahMouseReleased(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 60, 60));

        txt_namakategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_namakategori.setBorder(null);
        txt_namakategori.setOpaque(false);
        txt_namakategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namakategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txt_namakategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 180, 30));

        txt_idkategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idkategori.setBorder(null);
        txt_idkategori.setOpaque(false);
        txt_idkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idkategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, 30));

        labelKategori1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelKategori1.setForeground(new java.awt.Color(34, 48, 96));
        labelKategori1.setText("Nama Kategori");
        getContentPane().add(labelKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, 30));

        labelKategori.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelKategori.setForeground(new java.awt.Color(34, 48, 96));
        labelKategori.setText("ID Kategori");
        getContentPane().add(labelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        fieldIdBarang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text field nama kategori.png"))); // NOI18N
        getContentPane().add(fieldIdBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 190, 30));

        fieldIdBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text fielld id barang.png"))); // NOI18N
        getContentPane().add(fieldIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 30));

        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/edit-text 1.png"))); // NOI18N
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 60, 60));

        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/delete (2) 1.png"))); // NOI18N
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHapusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHapusMouseReleased(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 60, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Frame 13.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_kategoriMouseClicked
        int row = tb_kategori.getSelectedRow();
        this.selectedKategoriID = tb_kategori.getValueAt(row, 0).toString();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_kategori WHERE id_kategori ='" + selectedKategoriID + "'");
            while (rs.next()) {
                txt_idkategori.setText(rs.getString("id_kategori"));
                txt_namakategori.setText(rs.getString("nama_kategori"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DaftarKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_kategoriMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
    String idkategori = txt_idkategori.getText();
    String nama = txt_namakategori.getText();
    
    if (idkategori.isEmpty() || nama.isEmpty()) {
        throw new CustomException("ID Kategori dan Nama Tidak Boleh Kosong");
    } else {
        PreparedStatement ps = con.prepareStatement("INSERT INTO tb_kategori VALUES(?, ?)");
        ps.setString(1, idkategori);
        ps.setString(2, nama);
        
        ps.execute();
        
        JOptionPane.showMessageDialog(null, "Data kategori berhasil ditambahkan");
        tampilkan();
        reset();
    }
} catch (SQLException ex) {
    Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
} catch (CustomException ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
}

// User Defined Exception


    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Hover.png")));
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah.png")));
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
    String idkategori = txt_idkategori.getText();
    String nama = txt_namakategori.getText();
    
    if (idkategori.isEmpty() || nama.isEmpty()) {
        throw new CustomException("ID Kategori dan Nama tidak boleh kosong");
    } else {
        PreparedStatement ps = con.prepareStatement("UPDATE tb_kategori SET id_kategori = ?, nama_kategori = ? WHERE id_kategori = ?");
        ps.setString(1, idkategori);
        ps.setString(2, nama);
        ps.setString(3, this.selectedKategoriID);
        
        ps.execute();
        
        JOptionPane.showMessageDialog(null, "Data kategori berhasil diubah");
        tampilkan();
        con.close();
    }
} catch (SQLException ex) {
    Logger.getLogger(DaftarKategori.class.getName()).log(Level.SEVERE, null, ex);
} catch (CustomException ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
}

// User Defined Exception


    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Hover.png")));
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit.png")));
    }//GEN-LAST:event_btnEditMouseExited

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try {
            int hapus = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus data kategori?", "Hapus",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (hapus == JOptionPane.YES_OPTION) {
                if (this.selectedKategoriID == null) {
                    JOptionPane.showMessageDialog(null, "Pilih kategori yang ingin dihapus");
                } else {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
                    PreparedStatement ps = con.prepareStatement("DELETE FROM tb_kategori WHERE id_kategori = '" + this.selectedKategoriID + "'");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Data kategori berhasil dihapus");
                    tampilkan();
                    reset();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Tidak bisa dihapus karena terdapat data kategori di transaksi");
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Hover.png")));
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus.png")));
    }//GEN-LAST:event_btnHapusMouseExited

    private void txt_namakategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namakategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namakategoriActionPerformed

    private void txt_idkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idkategoriActionPerformed

    private void btnTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMousePressed
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Press.png")));
    }//GEN-LAST:event_btnTambahMousePressed

    private void btnEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMousePressed
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Press.png")));
    }//GEN-LAST:event_btnEditMousePressed

    private void btnHapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMousePressed
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Press.png")));
    }//GEN-LAST:event_btnHapusMousePressed

    private void btnTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseReleased
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Hover.png")));
    }//GEN-LAST:event_btnTambahMouseReleased

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Hover.png")));
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnHapusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseReleased
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Hover.png")));
    }//GEN-LAST:event_btnHapusMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarKategori().setVisible(true);
            }
        });
    }
class CustomException extends Exception {
    public CustomException(String message) {
        super(message);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JLabel fieldIdBarang;
    private javax.swing.JLabel fieldIdBarang1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelKategori1;
    private static javax.swing.JTable tb_kategori;
    public static javax.swing.JTextField txt_idkategori;
    public static javax.swing.JTextField txt_namakategori;
    // End of variables declaration//GEN-END:variables
}
