/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.text.NumberFormat;
import java.util.Locale;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 * @author Aryaaazr_
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    String tgl_format;
    String barangkeluar;
    public Dashboard(){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
//        System.out.printf("Harga Rupiah: %s %n", kursIndonesia.format(harga));
        initComponents();
        java.util.Date tgl = new java.util.Date();  
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("ddMMyy");
        tgl_format = kal.format(tgl);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos","root","");
            String sql_barangkeluar = "SELECT SUM(jumlah) AS jumlah FROM tb_detail_penjualan WHERE id_penjualan LIKE 'TJ"+tgl_format+"%'";
            String sql_omset = "SELECT SUM(total_harga) AS total FROM tb_penjualan WHERE id_penjualan LIKE 'TJ"+tgl_format+"%'";
            String sql_pengeluaran = "SELECT SUM(harga_pengeluaran) AS total_pengeluaran FROM tb_pengeluaran WHERE id_pengeluaran LIKE 'TL"+tgl_format+"%'";
            String sql_laba = "SELECT SUM((tb_barang.harga_jual - tb_barang.harga_beli )*tb_detail_penjualan.jumlah) as total_laba FROM tb_detail_penjualan JOIN tb_barang ON tb_detail_penjualan.id_barang = tb_barang.id_barang WHERE tb_detail_penjualan.id_penjualan LIKE 'TJ"+tgl_format+"%'";
//        "+tgl_format+"%
            ResultSet rs_barangkeluar = con.createStatement().executeQuery(sql_barangkeluar);
            ResultSet rs_omset = con.createStatement().executeQuery(sql_omset);
            ResultSet rs_pengeluaran = con.createStatement().executeQuery(sql_pengeluaran);
            ResultSet rs_laba = con.createStatement().executeQuery(sql_laba);
            if(rs_barangkeluar.next()){
                if(rs_barangkeluar.getString("jumlah")!= null){
                    txt_barangkeluar.setText(rs_barangkeluar.getString("jumlah")+" Buah");
                } else txt_barangkeluar.setText("0 Buah");
            }
            if(rs_omset.next()){
                if(rs_omset.getString("total")!= null){
                    txt_omset.setText(kursIndonesia.format(rs_omset.getInt("total")));
                } else txt_omset.setText("Rp. 0");
            }
            if(rs_pengeluaran.next()){
                if(rs_pengeluaran.getString("total_pengeluaran")!= null){
                    txt_pengeluaran.setText(kursIndonesia.format(rs_pengeluaran.getInt("total_pengeluaran")));
                } else txt_pengeluaran.setText("Rp. 0");
            }
            if(rs_laba.next()){
                if(rs_laba.getString("total_laba")!= null){
                    txt_laba.setText(kursIndonesia.format(rs_laba.getInt("total_laba")));
                } else txt_laba.setText("Rp. 0");
            }
        } catch(SQLException ex){
        }
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        if(Login.status.equals("kasir")){
        labelSelamatDatang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Selamat Datang Kasir.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pengeluaran = new javax.swing.JLabel();
        txt_laba = new javax.swing.JLabel();
        txt_barangkeluar = new javax.swing.JLabel();
        txt_omset = new javax.swing.JLabel();
        labelSelamatDatang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Dashboard");
        setInheritsPopupMenu(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pengeluaran.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_pengeluaran.setForeground(new java.awt.Color(34, 48, 96));
        txt_pengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_pengeluaran.setText("0");
        getContentPane().add(txt_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 160, -1));

        txt_laba.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_laba.setForeground(new java.awt.Color(34, 48, 96));
        txt_laba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_laba.setText("0");
        getContentPane().add(txt_laba, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 160, -1));

        txt_barangkeluar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_barangkeluar.setForeground(new java.awt.Color(34, 48, 96));
        txt_barangkeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_barangkeluar.setText("0");
        txt_barangkeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txt_barangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 170, 30));

        txt_omset.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_omset.setForeground(new java.awt.Color(34, 48, 96));
        txt_omset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_omset.setText("0");
        getContentPane().add(txt_omset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 160, -1));

        labelSelamatDatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSelamatDatang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Selamat Datang Admin.png"))); // NOI18N
        labelSelamatDatang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelSelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 430, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Background Dashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1018, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelSelamatDatang;
    private javax.swing.JLabel txt_barangkeluar;
    private javax.swing.JLabel txt_laba;
    private javax.swing.JLabel txt_omset;
    private javax.swing.JLabel txt_pengeluaran;
    // End of variables declaration//GEN-END:variables
}
