/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import config.Config;
import java.awt.Color;
import java.awt.Font;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
//import static wawonpahlawan.Karyawan.model;

/**
 *
 * @author Aryaaazr_
 */
public class Pengeluaran extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pengeluaran
     */
    static String selectedPengeluaranID;
    static DefaultTableModel model;

    public Pengeluaran() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        tb_pengeluaran.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 12));
        tb_pengeluaran.getTableHeader().setOpaque(false);
        tb_pengeluaran.getTableHeader().setBackground(new Color(34, 48, 96));
        tb_pengeluaran.getTableHeader().setForeground(new Color(255, 255, 255));
        tb_pengeluaran.getRowHeight(25);
        idPengeluaran();
        tampilkan();
    }

    public static void idPengeluaran() {
        try {
            java.util.Date tgl = new java.util.Date();
            java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("ddMMyy");
            String tgl_format = kal.format(tgl);
            Connection con = (Connection) Config.configDB();
            String sql = "SELECT MAX(id_pengeluaran) AS id_pengeluaran FROM tb_pengeluaran WHERE id_pengeluaran LIKE 'TL" + tgl_format + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String Nol = "";
                if (rs.getString("id_pengeluaran") == null) {
                    Nol = "000";
                    txt_idpengeluaran.setText("TL" + tgl_format + Nol + "1");
                } else {
                    String NoJual = rs.getString("id_pengeluaran").substring(8);
                    String AN = "" + (Integer.valueOf(NoJual) + 1);

                    if (AN.length() == 1) {
                        Nol = "000";
                    } else if (AN.length() == 2) {
                        Nol = "00";
                    } else if (AN.length() == 3) {
                        Nol = "0";
                    } else if (AN.length() == 4) {
                        Nol = "";
                    }
                    txt_idpengeluaran.setText("TL" + kal.format(tgl) + Nol + AN);//sesuaikan dengan variable namenya
                }
            }
            rs.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }

    public static void tampilkan() {
        String[] judul = {"ID", "Tanggal", "Nama Pengeluaran", "Harga"};
        model = new DefaultTableModel(judul, 0);
        tb_pengeluaran.setModel(model);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_pengeluaran");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pengeluaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void reset() {
        txt_namapengeluaran.setText("");
        txt_harga.setText("");
        idPengeluaran();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_namapengeluaran = new javax.swing.JTextField();
        ImageTxtNamaBarang = new javax.swing.JLabel();
        labelIdTransaksi1 = new javax.swing.JLabel();
        LabelPengeluaran = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        ImageTxtHarga = new javax.swing.JLabel();
        labelIdTransaksi2 = new javax.swing.JLabel();
        txt_idpengeluaran = new javax.swing.JTextField();
        ImageTxtNamaBarang1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pengeluaran = new javax.swing.JTable();
        btnTambah = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_pengeluaran = new javax.swing.JComboBox<>();
        labelIdTransaksi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1037, 557));
        setPreferredSize(new java.awt.Dimension(1037, 557));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_namapengeluaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_namapengeluaran.setBorder(null);
        txt_namapengeluaran.setOpaque(false);
        getContentPane().add(txt_namapengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 280, 30));

        ImageTxtNamaBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text field.png"))); // NOI18N
        getContentPane().add(ImageTxtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 30));

        labelIdTransaksi1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelIdTransaksi1.setForeground(new java.awt.Color(34, 48, 96));
        labelIdTransaksi1.setText("Nama ");
        getContentPane().add(labelIdTransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 30));

        LabelPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Icon Pengeluaran.png"))); // NOI18N
        getContentPane().add(LabelPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelHarga.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHarga.setForeground(new java.awt.Color(34, 48, 96));
        labelHarga.setText("Harga");
        getContentPane().add(labelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 50, 30));

        txt_harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_harga.setText("0");
        txt_harga.setBorder(null);
        txt_harga.setOpaque(false);
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 280, 30));

        ImageTxtHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text field.png"))); // NOI18N
        getContentPane().add(ImageTxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, 30));

        labelIdTransaksi2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelIdTransaksi2.setForeground(new java.awt.Color(34, 48, 96));
        labelIdTransaksi2.setText("Id Pengeluaran");
        getContentPane().add(labelIdTransaksi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 30));

        txt_idpengeluaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idpengeluaran.setBorder(null);
        txt_idpengeluaran.setEnabled(false);
        txt_idpengeluaran.setOpaque(false);
        getContentPane().add(txt_idpengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 280, 30));

        ImageTxtNamaBarang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text field.png"))); // NOI18N
        getContentPane().add(ImageTxtNamaBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 30));

        tb_pengeluaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tb_pengeluaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_pengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_pengeluaran.setFocusable(false);
        tb_pengeluaran.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_pengeluaran.setRowHeight(25);
        tb_pengeluaran.getTableHeader().setReorderingAllowed(false);
        tb_pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_pengeluaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 920, 340));

        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah.png"))); // NOI18N
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTambahMouseReleased(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 60, 60));

        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit.png"))); // NOI18N
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 60, 60));

        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus.png"))); // NOI18N
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHapusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHapusMouseReleased(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Background Penjualan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        cmb_pengeluaran.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_pengeluaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Pengeluaran" }));
        cmb_pengeluaran.setOpaque(false);
        cmb_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 300, 30));

        labelIdTransaksi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelIdTransaksi.setForeground(new java.awt.Color(34, 48, 96));
        labelIdTransaksi.setText("Jenis Pengeluaran");
        getContentPane().add(labelIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_pengeluaranActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
    int harga = Integer.parseInt(txt_harga.getText());
    
    if (txt_namapengeluaran.getText().isEmpty()) {
        throw new CustomException("Nama pengeluaran tidak boleh kosong");
    } else {
        PreparedStatement ps = con.prepareStatement("INSERT INTO tb_pengeluaran VALUES(?, NOW(), ?, ?)");
        ps.setString(1, txt_idpengeluaran.getText());
        ps.setString(2, txt_namapengeluaran.getText());
        ps.setInt(3, harga);
        ps.execute();
        JOptionPane.showMessageDialog(null, "Data pengeluaran berhasil ditambahkan");
        idPengeluaran();
        tampilkan();
        reset();
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(rootPane, "Masukkan angka dengan benar");
} catch (SQLException ex) {
    if (ex.getMessage().contains("Duplicate entry")) {
        JOptionPane.showMessageDialog(rootPane, "ID Pengeluaran telah terdaftar");
    } else {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
} catch (CustomException ex) {
    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}

// User Defined Exception


    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Hover.png")));
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah.png")));
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMousePressed
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Press.png")));
    }//GEN-LAST:event_btnTambahMousePressed

    private void btnTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseReleased
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Hover.png")));
    }//GEN-LAST:event_btnTambahMouseReleased

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
    int harga = Integer.parseInt(txt_harga.getText());
    
    if (txt_namapengeluaran.getText().isEmpty()) {
        throw new CustomException("Nama pengeluaran tidak boleh kosong");
    } else {
        PreparedStatement ps = con.prepareStatement("UPDATE tb_pengeluaran SET nama_pengeluaran = ?, harga_pengeluaran = ? WHERE id_pengeluaran = ?");
        ps.setString(1, txt_namapengeluaran.getText());
        ps.setInt(2, harga);
        ps.setString(3, txt_idpengeluaran.getText());
        ps.execute();
        JOptionPane.showMessageDialog(null, "Data pengeluaran berhasil diedit");
        tampilkan();
        reset();
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Masukkan harga dengan benar");
} catch (SQLException ex) {
    Logger.getLogger(Pengeluaran.class.getName()).log(Level.SEVERE, null, ex);
} catch (CustomException ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
}

// User Defined Exception


    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Hover.png")));
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit.png")));
    }//GEN-LAST:event_btnEditMouseExited

    private void btnEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMousePressed
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Press.png")));
    }//GEN-LAST:event_btnEditMousePressed

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Hover.png")));
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try {
            int hapus = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus data pengeluaran?", "Hapus",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (hapus == JOptionPane.YES_OPTION) {
                if (this.selectedPengeluaranID == null) {
                    JOptionPane.showMessageDialog(null, "Pilih karyawan yang ingin dihapus");
                } else {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
                    PreparedStatement ps = con.prepareStatement("DELETE FROM tb_pengeluaran WHERE id_pengeluaran = '" + this.selectedPengeluaranID + "'");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Data pengluaran berhasil dihapus");
                    idPengeluaran();
                    tampilkan();
                    reset();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Tidak bisa dihapus karena terdapat data pengeluaran di transaksi");
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Hover.png")));
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus.png")));
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnHapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMousePressed
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Press.png")));
    }//GEN-LAST:event_btnHapusMousePressed

    private void btnHapusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseReleased
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Hover.png")));
    }//GEN-LAST:event_btnHapusMouseReleased

    private void tb_pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pengeluaranMouseClicked
        int row = tb_pengeluaran.getSelectedRow();
        this.selectedPengeluaranID = tb_pengeluaran.getValueAt(row, 0).toString();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos", "root", "");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_pengeluaran WHERE id_pengeluaran ='" + this.selectedPengeluaranID + "'");
            while (rs.next()) {
                txt_idpengeluaran.setText(rs.getString("id_pengeluaran"));
                txt_namapengeluaran.setText(rs.getString("nama_pengeluaran"));
                txt_harga.setText(rs.getString("harga_pengeluaran"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_pengeluaranMouseClicked

class CustomException extends Exception {
    public CustomException(String message) {
        super(message);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageTxtHarga;
    private javax.swing.JLabel ImageTxtNamaBarang;
    private javax.swing.JLabel ImageTxtNamaBarang1;
    private javax.swing.JLabel LabelPengeluaran;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnTambah;
    private static javax.swing.JComboBox<String> cmb_pengeluaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelIdTransaksi;
    private javax.swing.JLabel labelIdTransaksi1;
    private javax.swing.JLabel labelIdTransaksi2;
    private static javax.swing.JTable tb_pengeluaran;
    public static javax.swing.JTextField txt_harga;
    public static javax.swing.JTextField txt_idpengeluaran;
    public static javax.swing.JTextField txt_namapengeluaran;
    // End of variables declaration//GEN-END:variables
}
