/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import java.awt.SplashScreen;

/**
 *
 * @author Aryaaazr_
 */
public class StartUp extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public StartUp() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingBar = new javax.swing.JProgressBar();
        loadingLabel = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBar.setBackground(new java.awt.Color(0, 51, 204));
        loadingBar.setForeground(new java.awt.Color(153, 255, 153));
        loadingBar.setAutoscrolls(true);
        loadingBar.setBorderPainted(false);
        loadingBar.setFocusable(false);
        loadingBar.setName(""); // NOI18N
        loadingBar.setRequestFocusEnabled(false);
        loadingBar.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 290, 20));

        loadingLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(34, 48, 96));
        loadingLabel.setText("Memuat .");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 200, 20));
        loadingLabel.getAccessibleContext().setAccessibleName("Loading.");

        loadingValue.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(34, 48, 96));
        loadingValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loadingValue.setText("0%");
        jPanel1.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 30, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Background Start Up.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        // loading process
        StartUp loading = new StartUp();
        loading.setVisible(true);
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                loading.loadingValue.setText(i + "%");
                if (i == 5) {
                    loading.loadingLabel.setText("Memuat . .");
                }
                if (i == 15) {
                    loading.loadingLabel.setText("Memuat . . .");
                }
                if (i == 20) {
                    loading.loadingLabel.setText("Menghubungkan Database .");
                }
                if (i == 30) {
                    loading.loadingLabel.setText("Menghubungkan Database . .");
                }
                if (i == 40) {
                    loading.loadingLabel.setText("Menghubungkan Database . . .");
                }
                if (i == 50) {
                    loading.loadingLabel.setText("Menghubungkan Berhasil . . .");
                }
                if (i == 60) {
                    loading.loadingLabel.setText("Aplikasi sedang diproses .");
                }
                if (i == 70) {
                    loading.loadingLabel.setText("Aplikasi sedang diproses . .");
                }
                if (i == 80) {
                    loading.loadingLabel.setText("Aplikasi sedang diproses . . .");
                }
                if (i == 100) {
                    loading.loadingLabel.setText("Berhasil . . !");
                }
                loading.loadingBar.setValue(i);
            } 
            new Home().setVisible(true);
            loading.dispose();
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
}
